### ISSUE TITLE
Hoverable details in graph

### ISSUE THREAD

**Issue by NickColley** [pouchdb/dashboard#2]
Looking at some other perf graphs it's really nice to be able to drill into the seperate nodes on the graph and get exactly which commit and data it represents.
Some examples:
http://bench.topcoat.io/
http://arewefastyet.com/

**Comment by daleharvey** [comment]
In particular for this we really want to be able to see the commit that related to the change

**Comment by virgie** [comment]
Currently have blank boxes on hover, will add in details

**Comment by virgie** [comment]
To avoid conflicts, I'll wait for #9 to be merged in before adding in the details

**Comment by daleharvey** [comment]
fixed in: https://github.com/pouchdb/dashboard/commit/059f250448a32a0ab9f00a13bbc2caa48ed1d7cc
