### ISSUE TITLE
Data visualisation for user usage of different backends.

### ISSUE THREAD

**Issue by NickColley** [pouchdb/dashboard#4]
PouchDB covers a lot of bases but most web developers I've talked to don't know much about the databases that ship with browsers or their market share.

If we could visualise this for a user it'll give them a clear understanding of who they're supporting, my proposal is something similar to http://www.iwanttouse.com/ but specific to pouchdb.

This could also potentially tie into the performance data so we could have performance to browser share ratio, you want to know what the performance will be like for the majority of your users without having to research indexeddb etc.

**Comment by nolanlawson** [comment]
- http://caniuse.com/sql-storage
- http://caniuse.com/indexeddb
- http://caniuse.com/namevalue-storage (when localStorage adapter gets merged!)

The tougher thing is explaining the ES5 environment and when you might need the shims.  Browser support is patchy; sometimes one method (e.g. `Array.prototypeforEach()`) is supported, whereas another one (`Function.prototype.bind()`) is not.

**Comment by NickColley** [comment]
I was thinking we give the information against the custom build, so if you get the indexeddb build for instance it'd tell you how many browsers it supports.

**Comment by nolanlawson** [comment]
Yeah, but we don't have custom builds yet.  :(  For now, we essentially have three builds: node (via npm), browser (via bower/download), and browser + ES5 shims (which probably everyone should use, unless they really want to punish users on older browsers).

**Comment by NickColley** [comment]
Closing out old issues.
