### ISSUE TITLE
Start using real data

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/dashboard#5]
http://pouchdb.github.io/dashboard/ is currently using a sample of data from http://pouchdb.cloudant.com/performance_results, switch it to using live data

**Comment by vw52** [comment]
I was trying to do this, but couldn't get the XMLHttpRequest or JSONP working. Could you direct me to a resource on how to query cloudant?

**Comment by daleharvey** [comment]
So we should dogfood pouchdb for this, one second I will try something out

One thing to remember is that xhr wont work on sites served from your filesystem, it needs to be a domain, I do `python -m SimpleHTTPServer` in the dashboard directory, then you can see the page @ http://127.0.0.1:8000/

**Comment by daleharvey** [comment]
heh surprised this worked first time

```
<html>
  <head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
  </head>
  <body>

    <script src="http://cdn.jsdelivr.net/pouchdb/2.1.0/pouchdb.min.js"></script>
    <script>
      var db = new PouchDB('http://pouchdb.cloudant.com/performance_results');
      db.allDocs().then(function(docs) {
        console.log(docs);
      });
    </script>
  </body>
</html>
```

http://junk.arandomurl.com/test.html

**Comment by daleharvey** [comment]
fixed in: https://github.com/virgie/dashboard/commit/bc076265d5c54b194e46738fec95dfe191b6072f
