### ISSUE TITLE
Add information to formatted results

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/dashboard#6]
So theres a few ways we need to change the data reported
1. We need to change the _id to be date so _all_docs can be queried by date, right now we can do that in memory, but its slow and wont scale, eventually we will need views, but right now just ordering by date should get us enough
2. need to specify the browser that the tests were run in
3. Need to add the commit hash to drill down

This should be a fairly simple PR to https://github.com/pouchdb/pouchdb/blob/master/bin/test-browser.js

**Comment by daleharvey** [comment]
Its worth mentioning the _id should be the date of the commit, however for now we only run the performance tests on commit so its fine as it is, when we backfill results we need to be careful

**Comment by daleharvey** [comment]
Also need to add what branch we were on, by default we should only show master

**Comment by daleharvey** [comment]
I filed a PR against pouch for this - https://github.com/pouchdb/pouchdb/pull/1996

**Comment by nolanlawson** [comment]
I filed a bonus PR to add browser info, presumably it could be indexed separately in a view, e.g. `emit([client.browser.name, client.browser.version])`: pouchdb/pouchdb#1997

**Comment by daleharvey** [comment]
merged
